# Generated by Django 5.1.7 on 2025-04-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_pessoal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='foto',
        ),
    ]
